language: python
python:
  - "3.7"
  # PyPy versions
#  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
#  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python3.7 -m unittest discover -s ./core -p "*_test.py" -v
